#!/usr/bin/env bash 
# bu nese eliyir
file="/etc/passwd"
while IFS=:  read -r user pass uid gid ui home CS
do 
	echo "The user $user is part of the $gid gang, lives in $home and rides $CS. $uid's place is protected by the passcode $pass, more info about the user here: $ui "
done  < $file
