#!/usr/bin/env bash 
# bu nese eliyir
i=1
while [ $i -lt 21 ]; do
 if [ $i -eq 5 ]; then
        echo "bad luck from China"
	echo "5"
        i=$((i+1))
 elif [ $i -eq 10 ]; then 
        echo "bad luck from Japan"
	echo "10"
        i=$((i+1))
 elif [ $i -eq 19 ]; then
	echo "bad luck from Italy"
        echo "19"
	i=$((i+1))
 else  
        echo "$i"
        i=$((i+1))
 fi
done
