#!/usr/bin/env bash 
# bu nese eliyir
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
sleep 10
trap 'rm -f  "/var/run/myscript.pid"' SIGQUIT 
while true; do 
        echo "To infinity and beyound"
done
